# ---------- Figure configuration ---------------
# title: "Den520d"
fig_width: 6
fig_height: 4
set_legend: true
legend_size: 12
y_grid: true
x_grid: false
output: "local/tmp.png"

marker_size: 10
line_width: 2.0
marker_width: 2.0
alpha: 1.0
set_shift: 0
text_size:
  title: 10
  x_axis: 12
  y_axis: 12
# ---------- End: Figure configuration ----------


# ---------- Instance configuration -------------
ins_num:    25
time_limit: 60
succ_only:  false
is_std: false
is_ci: false

y_axis:
  label: "Success rate"
  scale: 1
  range: [0, 0.2, 0.4, 0.6, 0.8, 1.0]
  script: "script/operate.py"

x_axis:
  label: "Number of agents"  # "Suboptimality factor"
  range: [200, 400, 600, 800]

# ---------- End: Instance configuration --------


plots:
  - label: "ECBS(w:1.01)"
    color: "grey"
    markerfacecolor: "white"
    marker: "X"
    zorder: 0
    data:
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_200_1.01_ECBS.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_400_1.01_ECBS.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_600_1.01_ECBS.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_800_1.01_ECBS.csv"

  - label: "ECBS-BP(w:1.01)"
    color: "deepskyblue"
    markerfacecolor: "white"
    marker: "o"
    zorder: 1
    data:
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_200_1.01_ECBS-BP.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_400_1.01_ECBS-BP.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_600_1.01_ECBS-BP.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_800_1.01_ECBS-BP.csv"

  - label: "ECBS-BP-WDG(w:1.01)"
    color: "pink"
    markerfacecolor: "white"
    marker: "P"
    zorder: 2
    data:
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_200_1.01_ECBS-BP-WDG.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_400_1.01_ECBS-BP-WDG.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_600_1.01_ECBS-BP-WDG.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_800_1.01_ECBS-BP-WDG.csv"

  - label: "FECBS-BP(w:1.01)"
    color: "red"
    markerfacecolor: "white"
    marker: "^"
    zorder: 3
    data:
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_200_1.01_FECBS-BP.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_400_1.01_FECBS-BP.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_600_1.01_FECBS-BP.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_800_1.01_FECBS-BP.csv"

  - label: "FECBS-BP-WDG(w:1.01)"
    color: "green"
    markerfacecolor: "white"
    marker: "s"
    zorder: 4
    data:
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_200_1.01_FECBS-BP-WDG.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_400_1.01_FECBS-BP-WDG.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_600_1.01_FECBS-BP-WDG.csv"
      - - "/home/rdaneel/AAAI_results/Paris-1-256/ECBS/Paris-1-256_random_800_1.01_FECBS-BP-WDG.csv"
